### PR TITLE
Add keep-tree option to permit to keep tree on include dir when install

### PR DESCRIPTION
**Pull request by barraudl**
Signed-off-by: barraudl <lilianbarraud@eaton.com>

### CODE REVIEW

**Comment by bluca** [comment]
Looks like regenerating leads to an error:

```
Makefile.am:17: error: required directory ./include does not exist
Makefile.am:19: error: required directory ./include does not exist
```

Could you please have a look at it?

**Comment by bluca** [comment]
@barraudl regenerating CZMQ removes a bunch of stuff from Makefile.am:

```
+++ b/src/Makemodule.am
@@ -12,49 +12,6 @@ endif
 lib_LTLIBRARIES += src/libczmq.la
 pkgconfig_DATA = src/libczmq.pc
 
-include_HEADERS = \
-    include/czmq_prelude.h \
-    include/czmq.h \
-    include/zactor.h \
-    include/zarmour.h \
-    include/zcert.h \
-    include/zcertstore.h \
-    include/zchunk.h \
-    include/zclock.h \
-    include/zconfig.h \
-    include/zdigest.h \
-    include/zdir.h \
-    include/zdir_patch.h \
-    include/zfile.h \
-    include/zframe.h \
-    include/zhash.h \
-    include/zhashx.h \
-    include/ziflist.h \
-    include/zlist.h \
-    include/zlistx.h \
-    include/zloop.h \
-    include/zmsg.h \
-    include/zpoller.h \
-    include/zsock.h \
-    include/zstr.h \
-    include/zsys.h \
-    include/zuuid.h \
-    include/zauth.h \
-    include/zbeacon.h \
-    include/zgossip.h \
-    include/zmonitor.h \
-    include/zproxy.h \
-    include/zrex.h \
-    include/czmq_library.h
-
-if ENABLE_DRAFTS
-include_HEADERS += \
-    include/zargs.h \
-    include/zproc.h \
-    include/ztimerset.h \
-    include/ztrie.h
-
-endif
```

Could you please have a look?

**Comment by bluca** [comment]
Ah there's a new file to include, never mind

**Comment by sappo** [comment]
@barraudl thanks for your contribution :) For future PRs please read the contribution guideline more carefully especially describe Problem and Solution in your commits.

**Pull request merged**
