### PR TITLE
Problem: ZPROJECT does not have a visual CONTRIBUTING guide

### PR DESCRIPTION
**Pull request by opedroso**
Solution: Added CONTRIBUTING.docx visual guide on how to make a contribution.

* Also made added a reference to README.txt and regenerated README.md to this new
visual guide.

The generation of README.md was done by running this command on Ubuntu 14.04:
```sh
	$ gitdown README.txt
```

### CODE REVIEW

**Comment by hintjens** [comment]
Please don't add docx files. We use CONTRIBUTING.md in other projects.

**Comment by jemc** [comment]
Docx files are (1) a proprietary format and (2) totally opaque to revision control systems like git, so they're not suitable for inclusion in projects like this.

I haven't reviewed the contents, since I don't have any software that reads docx files, but I assume any relevant information could be included in markdown format.  It would be possible to include small images as well, but I can't think of any reason that would relevant for this project, which is non-visual in nature, so screenshots wouldn't be particularly helpful.

**Comment by opedroso** [comment]
Anybody can open a DOCX file using docs.google.com using non-proprietary software.
Would formatting the file in PDF, RTF, XML, or EPUB help?
I believe it would be useful even for non Windows users by showing how to contribute to the project.
Are we really inclusive for all the community dwellers?

**Comment by opedroso** [comment]
Here is the content of the file in a readable, non-proprietary format:
https://docs.google.com/document/d/1ze-Dbs3yhq5DvOBMhM-wa0Nw62UuTR9V9Pw0fKXpUdY/edit?usp=sharing

I believe it would be useful even for non Windows users by showing how to
contribute to the project.

Are we really inclusive for all the community dwellers?
I can follow rules as long as they are stated.

Would formatting this file in PDF, RTF, XML, or EPUB or any other
acceptable format help?

**Comment by rgbkrk** [comment]
@opedroso I've noticed lots of your Windows fixes for zeromq/* - thank you so much for all your patches. I appreciate them.

As for docx vs md, I'd hold back from including a docx file since it is a binary format. It's really ugly to deal with in git, especially over time (unless using git LFS). While I don't set the rules here, I certainly wouldn't want to see this file in there.

However, the _content_ is good. Good places for this might be a personal org or blog for now.

**Comment by opedroso** [comment]
Hi Kyle,

Glad to hear. Hope to make many more contributions as I learn more. I am
helping where I can at this point in my zeromq journey.

I don't have a problem not checking in DOCX.

I am willing to convert to any other format that is deemed appropriate.
The only reason I attempted is because it is natural format for a Windows
developer and I did not see stated anywhere that this was frowned upon.

As I said, I can follow rules as well as anybody else.

**Comment by jdfreder** [comment]
I think .txt files are also natural for Windows developers and are cross-platform / open...  Although the differences between md and txt are almost null - your txt will probably end up looking like the .md file ;)

**Comment by opedroso** [comment]
I guess the question then is what is a natural cross-platform / open file
format that allows the expression of images in it that would be acceptable
to checkin to a zeromq project?
Extra points if Windows tools can generate that format as well, even if
they need to be open source tools built in Windows.

**Comment by rgbkrk** [comment]
Markdown allows for images using this syntax:

```
![](http://placehold.it/350x150)
```

Which can also work with relative paths:

```
![](images/click.gif)
```

Though I tend to upload images to a github issue then link that:

```
![image](https://cloud.githubusercontent.com/assets/836375/14433812/64218ab0-ffd5-11e5-829f-b36736dc2056.png)
```

**Comment by jdfreder** [comment]
Cross platform, my vote would be for md too.  md->html or md->rtf could be used for producing even friendly Win docs from a single base md doc.

**Pull request closed without merging**
