### PR TITLE
Problem: known_projects listed some github upstreams without the .git extension

### PR DESCRIPTION
**Pull request by jimklimov**
Solution: revise the list to always include the extension (less surprise in regenerated ci_build.sh scripts then); also fix imagix => imatix for GSL

### CODE REVIEW

**Comment by sappo** [comment]
@jimklimov we need to double check that the field hasn't been falsely used as URL.

**Comment by jimklimov** [comment]
This should not be a problem - I can open e.g. https://github.com/zeromq/zproject.git in the browser and get redirected to the https://github.com/zeromq/zproject root.

**Comment by sappo** [comment]
Except some smart guy appends the ".git" xD (i.e. Docker and Vagrant)

**Comment by jimklimov** [comment]
You mean lines like these?
````
RUN git clone --quiet $(use.repository).git $(use.project).git
RUN git clone --quiet git://github.com/zeromq/$(project.name:c).git $(project.name:c).git
````

I known the smart guy :) But AFAIK the names should be stripped of the `.git` extension (another bug to tackle, thanks). And some known repos had the extension and some did not.

PS: The benefit of real peer review rather than fast-merge ;)

**Comment by sappo** [comment]
Yes #737

**Pull request merged**
