### PR TITLE
Making gyp builds work on Windows, for CZMQ and Zyre

### PR DESCRIPTION
**Pull request by hintjens**

### CODE REVIEW

**Comment by c-rack** [comment]
:+1:

**Comment by hintjens** [comment]
Thanks. :)

Gyp works really nicely, in fact. It is brutal and simple. You can try this:

```
sudo apt-get install gyp
git clone https://github.com/zeromq/libzmq
git clone https://github.com/zeromq/czmq
git clone https://github.com/zeromq/zyre
cd zyre/builds/gyp
gyp --depth=. && make -j5
```

That's it. It builds its dependencies properly and gives static binaries in out/Default.

**Comment by c-rack** [comment]
Just tried it, works like a charm :-)

**Comment by hintjens** [comment]
:)

**Comment by c-rack** [comment]
As a Mac OS X user, I could not install `gyp` with `brew install gyp` directly, so I opened a PR for that:
https://github.com/Homebrew/homebrew/pull/49128

**Comment by hintjens** [comment]
Google won't tag it as they're deprecating it.

GYP is really just an excuse to use node-gyp, which uses the same project
format yet does rather a lot more with it... that's the next phase,

**Comment by c-rack** [comment]
OK, lesson learned :-)

**Pull request merged**
