### PR TITLE
Problem: [debian] packaging missing dsc and format required by OBS

### PR DESCRIPTION
**Pull request by sappo**
Solution: Add project dsc and format files

### CODE REVIEW

**Comment by bluca** [comment]
Mmh I actually removed this a while ago. It will break the package build, among other things on OBS when using a git service, since dpkg-scansources will find a duplicate dsc.

The dsc is generated at build time by dpkg-buildpackage/debuild

**Comment by sappo** [comment]
Okay, makes sense but OBS didn't start ubuntu/debian build without it.

**Comment by bluca** [comment]
Yes that depends on the type of build used - if you upload manually the tarballs and the artefacts, it will need a dsc.
But instead we can use a source service, for example:

https://github.com/jblunck/obs-service-git_buildpackage
https://github.com/01org/obs-service-git-buildpackage

(the latter supports RPMs too)

We do this at work, and the advantage is that the CI is much simpler. The service will take care of checking out the git tree and generating the artefacts with git-buildpackage -S, so the only thing you have to do from the hook is to kick a remote service run.

I am a bit swamped at work this week, but I can help on IRC, and have a go at it next week if you want

**Comment by sappo** [comment]
Cool, I'll check it out!

**Comment by bluca** [comment]
Great, ping me if you need some pointers.
Also, sorry, the debian/format change was good, and using 3.0 (quilt) is indeed correct :-)

**Pull request merged**
