### PR TITLE
Two patches

### PR DESCRIPTION
**Pull request by asokoloski**
The zproto headers one is the slightly more interesting one.

### CODE REVIEW

**Comment by asokoloski** [comment]
Thank you!

**Comment by sappo** [comment]
@asokoloski I'm note sure weather your first problem is valid. I agree that zproject messes up the zproto header. But you can restore that with `make code`. Thereby the API file is only effectively used by the bindings.

**Comment by asokoloski** [comment]
Hmm, ok.  I'm still a bit new to all this stuff, sorry.

This reasoning behind this is mainly coming from here:
https://github.com/zeromq/malamute/issues/115

But I'm not too bothered.  make code seems fine by me.

**Comment by asokoloski** [comment]
I'll push a revert.

**Comment by asokoloski** [comment]
I mean, revert and make a pull request :)

**Comment by sappo** [comment]
The zproject zproto integration currently doesn't work well. We should fix that!

**Pull request merged**
