### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by hintjens**

### CODE REVIEW

**Comment by paddor** [comment]
@hintjens Looks great, thank you. However, for some reason, the Ruby bindings generator skips the included zsock_option methods (even though they're actually included by `resolve_includes` (I verified) and at least get resolved in `resolve_ruby_method` (I verified)). But later in the `.for method` loop, they just get skipped and I have no idea why.

In case you know something off the top of your head, please let me know.

Otherwise I'll keep looking...

**Comment by hintjens** [comment]
No idea off the top of my head, I'll take a look though.

**Comment by paddor** [comment]
Thank you. (I'll be AFK for the next 3h.)

**Comment by paddor** [comment]
False alarm! It used to generate FFI-stuff for the zsock_option functions twice! Now it's correct. But of course the diff looked like it got removed. :+1:

**Pull request merged**
