### PR TITLE
Problem: Appending .git fails if repository already has suffix

### PR DESCRIPTION
**Pull request by sappo**
Solution: Except the .git suffix to be set by the repository
variable

### CODE REVIEW

**Comment by jimklimov** [comment]
Also makes sense for e.g. locally customized builds where the clone origin may be a directory and so can have or lack an extension. Just use what the XML provides. Sorry for the messup :)

:+1:

**Comment by sappo** [comment]
@jimklimov no worries, this is our way of working :) Keep up the good work :+1:

**Comment by jimklimov** [comment]
I'll try. Can't promise I won't keep up the occasional bad work too, though
;)

2016-12-09 10:58 GMT+01:00 Kevin Sapper <notifications@github.com>:

**Comment by bluca** [comment]
@sappo @jimklimov note that the python binding generation is also broken now:

```
--- a/bindings/python/malamute/_malamute_ctypes.py
+++ b/bindings/python/malamute/_malamute_ctypes.py
@@ -7,7 +7,7 @@ from __future__ import print_function
 import os, sys
 from ctypes import *
 from ctypes.util import find_library
-import czmq
+import czmq.git
 
 # malamute
 lib = None
@@ -57,15 +57,15 @@ lib.mlm_proto_new.argtypes = []
 lib.mlm_proto_destroy.restype = None
 lib.mlm_proto_destroy.argtypes = [POINTER(mlm_proto_p)]
 lib.mlm_proto_recv.restype = c_int
-lib.mlm_proto_recv.argtypes = [mlm_proto_p, czmq.zsock_p]
+lib.mlm_proto_recv.argtypes = [mlm_proto_p, czmq_git.zsock_p]
```

**Comment by jimklimov** [comment]
Not sure what I can do here, my Python is not that strong... Maybe @vyskocilm can chime in?..

Are the "minused" old lines the correct ones? Or on the contrary, should this import match the directory name (now with extension, for automated git clones of prerequisites) somehow?

And this diff probably comes from a selftest or project regeneration (of czmq?), and I see no PR about this... And there are no "git" hits in zproject_python*.gsl so the issue is not something I can easily and stupidly monkey-wrench, sorry :\

**Comment by bluca** [comment]
Yes it's the output of a regeneration from zproject. The Python class should not have a git extension, as it doesn't make much sense, but not sure where is picking that up - from the class template? Or the general one maybe?

**Comment by bluca** [comment]
Urgh can't reproduce it anymore today, not sure what's going on! I'll post back if I can

**Comment by sappo** [comment]
I'll have a look at it tomorrow

Am 11.12.2016 13:51 schrieb "Luca Boccassi" <notifications@github.com>:

**Comment by sappo** [comment]
@bluca I just checked the python bindings. The only way this diff can occur is if the libname and project name is 'czmq.git' or 'czmq_name' respectively.

**Comment by bluca** [comment]
yeah I can't reproduce anymore, not sure how it happened!

**Pull request merged**
