### PR TITLE
Problem: Cannot specify uint8-64_t types in class api

### PR DESCRIPTION
**Pull request by sappo**
Soltion: Use the xml syntax from zproto to add uint8-64_t types

### CODE REVIEW

**Comment by hintjens** [comment]
@sappo, nice stuff. I was trying to use these structures to generate code (JNI), and it's a little obscure. Could you have time to write down how the container structures work, for people writing binding generators?

**Comment by sappo** [comment]
@hintjens once I figured that stuff out myself, I'll try to document it :-D
I'm currently writing a binding for Qt and I think I'm finally close to having a good overview about the structures.

**Comment by hintjens** [comment]
Ah, cool, that will be awesome.

**Comment by jemc** [comment]
Since I wrote the first two of the binding generators, I can probably explain how they work.  I'll try to do a writeup later tonight or at the end of the week.

**Comment by twhittock** [comment]
I seem to remember using `XML.save` or similar to dump the document
structure after the initial passes were made - this was useful in
understanding what was going on.

**Comment by jemc** [comment]
@twhittock - Great idea!  I could mention that in the writeup as well and show an example output.

@sappo - Also, you probably already saw the QML bindings, but in case you didn't they should be very helpful in creating Qt bindings (I expect they would be almost the same).

**Comment by jemc** [comment]
See https://github.com/zeromq/zproject/pull/236

**Comment by sappo** [comment]
@jemc - That's the reason I weren't completely lost ;)

**Pull request merged**
