### PR TITLE
Problem: ztrie uses a char in its API to pass a delimiter which is not supported by zproject's API

### PR DESCRIPTION
**Pull request by sappo**
Solution: Add char as possible type

### CODE REVIEW

**Comment by twhittock** [comment]
what are the characteristics of 'char' ? signed byte? unsigned byte? should
we use names to describe the type, instead of talking about C types? That's
why byte is there already right?

**Comment by sappo** [comment]
Wow, you ask a lot of questions :P 
unsigned char. Maybe character instead of char. A char contains textual data whereas a byte can contain anything.

**Comment by hintjens** [comment]
Do you have a use case for a single char as compared to a short string? I
mean, what's the problem we're solving here ("lack of feature X" is not a
valid problem :)

**Comment by sappo** [comment]
ztrie uses a char as an argument to define the delimiter.

**Comment by sappo** [comment]
Example: `ztrie_new ('/');`

**Comment by hintjens** [comment]
Makes sense to me.

**Comment by sappo** [comment]
Shall I close this PR and open another with a commit that states the valid problem?

**Comment by sappo** [comment]
Okay I managed to change the commit message ;)

**Pull request merged**
