### PR TITLE
problem: makemodule missing zproject_vagrant.gsl

### PR DESCRIPTION
**Pull request by wesyoung**
needed to re-run and commit src/Makemodule.am

travis seems to have not complained on this build (my account):

https://travis-ci.org/wesyoung/zproject/builds/144563619

but might wanna check to see that it builds under this project just to be sure before merging.

### CODE REVIEW

**Comment by wesyoung** [comment]
im assuming as long as the "default" build succeed's that's normal?

**Comment by sappo** [comment]
Yep, the check_zproject won't succeed at a pull request if there are any changes to files generated by zproject.

**Comment by wesyoung** [comment]
hoookay. thx for the help :)

**Comment by bluca** [comment]
thanks for fixing it!

**Pull request merged**
