### PR TITLE
Problem: No support for python bindings

### PR DESCRIPTION
**Pull request by twhittock**
Solution: Generate Python bindings using ctypes

### CODE REVIEW

**Comment by jemc** [comment]
Cool!

**Comment by RonnyPfannschmidt** [comment]
Take a look at cffi as well

**Comment by jemc** [comment]
@RonnyPfannschmidt 
If there's a demand for it, we can support emitting both from zproject.

**Comment by RonnyPfannschmidt** [comment]
it might be a good idea to take a deeper look into cffi
the c binding modules it generates are faster, and have jit support on pypy

also unlike ctypes they do not generate gc pressure on python implementations without refcounting

**Comment by twhittock** [comment]
cffi isn't a standard module in python. i didn't want the hassle of having an extra barrier to entry (even as simple as `pip install cffi`). Are the ctypes calls actually causing a bottleneck for you? I wrote these for doing prototyping, so not really considering speed at all.

**Comment by RonnyPfannschmidt** [comment]
i'm not yet having any trouble, i raised this issue preventative

**Pull request merged**
