### PR TITLE
Problem: ci tests runs too long

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: make distcheck opt-in

### CODE REVIEW

**Comment by karolhrdina** [comment]
Quick discussion with @vyskocilm - Fix coming regarding failing check.

**Comment by bluca** [comment]
I strongly disagree with this change, and would like to revert it.

If it's optional, de-facto it will not run.

Dist-check is fundamental as the github and travis based releases generated by zproject rely on the dist tarball to work properly, and if it's not checked history teaches us that it will break, and then the people doing releases (ie: me :-) ) will have to scramble and do last-minute workarounds

**Comment by bluca** [comment]
How about, as a compromise, to make it opt out instead? So you can disable it in your project if you want (not recommended! :-) )

**Comment by bluca** [comment]
implemented in https://github.com/zeromq/zproject/pull/756 let me know if that causes you any issue

**Comment by vyskocilm** [comment]
Hi,

Wasn't aware about. We're using git archive most of the time, so there's a
little value and a lot of hurdles for it's.

So your change is good for us.

Dne 16. 12. 2016 16:04 napsal uživatel "Luca Boccassi" <
notifications@github.com>:

**Pull request merged**
