### PR TITLE
Problem: comment in control file breaks BuildService parser

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: drop it

### CODE REVIEW

**Comment by sappo** [comment]
@bluca added this comment to remind him/us not to remove systemd in the future. Is there any way to retain the comment without breaking the BuildService?

**Comment by jimklimov** [comment]
@sappo Is there a GSL comment tag?

**Comment by sappo** [comment]
@jimklimov excellent idea!

**Comment by bluca** [comment]
By build-service you mean OBS? It doesn't cause problems for example: https://build.opensuse.org/package/show/home:zeromq:git-stable/czmq

**Comment by bluca** [comment]
GSL comment works too, just curious about the failure since I haven't seen it

**Comment by jimklimov** [comment]
Michal is not around ATM, but I can guess that our (internal) OBS may be different both due to age and local tinkering/forking.

**Comment by vyskocilm** [comment]
Our problém was that with a comment dh-systemd wasn't installed. Once I
removed the line, system started to work again

Dne 5. 1. 2017 15:15 napsal uživatel "Jim Klimov" <notifications@github.com

**Pull request merged**
