### PR TITLE
Problem: cztx class in czmq is deprecated and removed

### PR DESCRIPTION
**Pull request by malanka**
Solution: change check zctx_test -> zhashx_test

### CODE REVIEW

**Comment by malanka** [comment]
And actually projects generated with zproject cannot be compiled, if all necessary CZMQ stuff is manually installed from sources

**Comment by jimklimov** [comment]
@malanka : If you install from sources, do you override path to PKGCONFIG directories to match your local installation? E.g. if you put `libzmq` ecosystem files under `/usr/local/lib`, you should configure your own project with `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:${PKG_CONFIG_PATH} ./configure`

(or just `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig` in your shell before playing)

This helped me when similar behavior bit me.

**Comment by malanka** [comment]
No, I didn't do this. But still, check for a class that does not exist anymore, is bad :)

**Comment by bluca** [comment]
Thanks, missed this when I retired those classes

**Pull request merged**
