### PR TITLE
Problem: project-local CMake hook are not included

### PR DESCRIPTION
**Pull request by aquette**
Solution: Fix typo error

Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>

### CODE REVIEW

**Comment by jimklimov** [comment]
Not a typo, `sinclude` is the silent-include keyword (see recent PR #860 that added it). AKA the `-include` in GNU make, to try including the file but not bomb out if it is missing (so we do not have to regenerate the zproject after adding the manually maintained file to codebase).

Namely, this change-back will break projects that do not have an `src/Makemodule-local.am` ;)

**Comment by jimklimov** [comment]
@sappo : you merged a not-yet-green PR (and it would end up red because zproject's Makefile.am was not amended to match the "fixed" template). That's beside not thinking about what you merge ;)

**Comment by jimklimov** [comment]
@aquette : does the change you proposed fix something on your builds (e.g. did `sinclude` break anything with a particular `make` implementation)?

**Comment by aquette** [comment]
@jimklimov sorry, I indeed misunderstood the behavior and wrongly thought that this should be expanded in the final Makefile, while it's indeed a runtime expansion... Reverting commit

**Pull request merged**
