### PR TITLE
Problem: there are serious technical concerns regarding splitted spec…

### PR DESCRIPTION
**Pull request by vyskocilm**
… files

Solution: Revert "Problem: build of czmq fails on platform w/o python2"

This reverts commit 2b8836a6d9cb45f9ab22da56760f13c5bf9bc95e.

### CODE REVIEW

**Comment by vyskocilm** [comment]
@bluca let test setup in OBS

**Comment by bluca** [comment]
I've set it up to set python_cffi only on newer RPM distros (having some troubles with the i586 arch, will get that done soon)

Should it instead be a new python3_cffi ? So that the python2 stuff is still built for older distros

**Comment by vyskocilm** [comment]
Hi,

Don't really understand your needs 😀 do whatever is best for you

Dne 21. 6. 2017 2:58 odpoledne napsal uživatel "Luca Boccassi" <
notifications@github.com>:

**Comment by bluca** [comment]
Cool, will take care of it later tonight

**Comment by vyskocilm** [comment]
I'll do my best as well... I am going to add two conditionals into the
project. Thanks especially for Debian. We want to use python bindings in
our new project a lot. So you will save our CI

Dne 21. 6. 2017 3:06 odpoledne napsal uživatel "Luca Boccassi" <
notifications@github.com>:

Cool, will take care of it later tonight

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zeromq/zproject/pull/921#issuecomment-310072304>, or mute
the thread

**Pull request merged**
